apiVersion: v1
kind: Service
metadata:
  name: customer-prediction-app-service
  namespace: customer
spec:
  selector:
    app: customer-prediction-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer

